[package]
name = "wfinfo-ng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
captrs = "0.3.1"
image = "0.24.3"
palette = "0.6.1"
serde = { version = "1.0.144", features = ["serde_derive"] }
serde-aux = "3.1.0"
serde_json = "1.0.85"
tesseract = "0.12.0"
