name: Rust
on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/actions/dependencies
      - uses: Swatinem/rust-cache@v2.7.3
      - name: Check
        run: |
          cargo clippy --workspace --all-features

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/actions/dependencies
      - uses: Swatinem/rust-cache@v2.7.3
      - name: Check
        run: |
          cargo fmt --check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/actions/dependencies
      - uses: Swatinem/rust-cache@v2.7.3
      - name: Check
        run: |
          cargo build --release
